# Generated by Django 5.0.4 on 2024-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='social_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
